# Generated by Django 4.0.2 on 2022-03-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sioapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
